language: python
python:
- '2.7'
- '3.3'
- '3.5'
- '3.6'
- pypy
- pypy3
install:
- pip install --upgrade setuptools #Needed for cryptography on Python3.3
- pip install -r requirements.txt
script: py.test --pylint --doctest-modules --ignore=setup.py
deploy:
  provider: pypi
  user: BarnabyShearer
  password:
    secure: i6Gm8xCN5QGftiwk0iRKd4csXKGS4EEFQVSu90GiyRw37thfG5K/rn0aiGB3KPWcN/xJ4Mcv0dRVQHwfusHFf1deUqUWqeatgo3MxWIdFk3CZVgOWPkXqqYS51xKjB7CF2Th+o9jYvzvVFg8DdqEZdu3quAcYGVriChesAutrdV3LWCWGxQkC7IP10lrQv8Hhv6L/YBb8fBvJeBjmq7wmKKF6TiDf0n/1O/OKPlZxffHcF5jktwdd+2EkXtgv0ZZQGuF0JuBP40czG2rLWIKjNA3RxEaaPGKjn5zrzT/Y/7M6jOpS3Eimuler1hPmEqvtiZPtYfkGb+l7FXua42bhskHD/yIDYFdjhj9yO9+gC/PQacfnJ5tD9yZF5rtyRhctYZa0MEi3gKr/Q+Y0PF3qwSdQ8qvMC3ZNROUvejWFbUhS/5mc4yNrzr3SbDTDzLv2khAUm/8fmZXCFB3PI98vlpaG2iK7/ji4gKR9asM+AD7lIoTabbm8BXiyl9aHGPkq/Kbu7yVuwAdNCIL3Qm+p59yumtRIjnBRvf0WTg23z2vu0Mi1qXZYtISUJHYHVjSX1KY7bqxMEZ6bSU8Zul58hsGfJCDV1WXQBS/9J3Rgtkqh1rkUcHrwucRA4XMZxksLkPCkbaltyhJhWd/w/ATIvnqBXexBCw5/1/+pE6iEi8=
  on:
    tags: true
